In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv("insurance_pre.csv")

In [3]:
data

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
data = pd.get_dummies(data,dtype=int, drop_first=True)
data.head()

   age     bmi  children      charges  sex_male  smoker_yes
0   19  27.900         0  16884.92400         0           1
1   18  33.770         1   1725.55230         1           0
2   28  33.000         3   4449.46200         1           0
3   33  22.705         0  21984.47061         1           0
4   32  28.880         0   3866.85520         1           0

In [5]:
independent = data[["age","sex_male","bmi","children","smoker_yes"]]
dependent = data[["charges"]]

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import AdaBoostRegressor
param_grid = {'n_estimators':[1,10,100,1000],
             'loss':['linear','square','exponential']}
grid = GridSearchCV(AdaBoostRegressor(random_state=0), param_grid,refit=True, verbose=3,n_jobs=-1,cv=3)
grid.fit(independent,dependent)

Fitting 3 folds for each of 12 candidates, totalling 36 fits

C:\Users\ELCOT\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=3, estimator=AdaBoostRegressor(random_state=0), n_jobs=-1,
             param_grid={'loss': ['linear', 'square', 'exponential'],
                         'n_estimators': [1, 10, 100, 1000]},
             verbose=3)

In [7]:
re=grid.cv_results_
grid_predictions = grid.predict(independent)

In [8]:
from sklearn.metrics import r2_score
r_score=r2_score(dependent,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'loss': 'linear', 'n_estimators': 1}: 0.8552200456449022

In [9]:
table=pd.DataFrame.from_dict(re)

In [10]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 45
BMI: 39
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [11]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[25979.61399741]

C:\Users\ELCOT\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but AdaBoostRegressor was fitted with feature names
  warnings.warn(